[[Clp]]
arch = "aarch64"
git-tree-sha1 = "4e24ac44bb05c317f71c0a21adf065ce3fe6a87a"
os = "macos"

    [[Clp.download]]
    sha256 = "31b36306ee24f7a3342e3b1345796861a3677e5483605f888144b4526f4eacd5"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.aarch64-apple-darwin.tar.gz"
[[Clp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00951620d95f154a3b1dfcbfd956078bda0214cc"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "d456d91a4dbcbb287553a08b8a1e0be986bb172a190136d50d4b3f202b0fc5ea"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.aarch64-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1965aad10d2961d3cde93f89f2b725b0d502de74"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "544818e842dbf88b93b53860b7b226bea72ba52631cab222b63da8a790eea225"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.aarch64-linux-musl-cxx11.tar.gz"
[[Clp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe768bc9324caa0fac2d66b0755892c4175dddd6"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "255880c8fa8932b3c511172007dd2d85dcfe61520f4821953640c0a5cc5feab0"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c09c0b3ea0bc76cb0176d281fbbb926245319c5"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "fc1600bf0419af64f0d92fb5bcf3cf4461fee7bd1643d9dc070ad5de236d2d86"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a0014b95d76d613bf33430fa0ae1c4cb2151ba5"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "1af6bffb0387eaa2258c319112e5923c2ca1de0a1b5e96b463706cb108a0d073"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b944ab5d466d9417296b9ae8dea5ccf80e2c902f"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "b4988477f1e0825d7b7cda817430ad49646e8f7158911cb01bddd5ebdcc0daf5"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cac476da23543fef6923f6025e25ce59a997b1b"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "e46da395de9db179c2939732f2934ee5c13b60a2647cd9af84806fd1d4c79c6b"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.i686-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e675d21cebcb6e9a1c2dec0b35a62c31a4573c1c"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "413186dabab6a08f09f3798a71ebdcc211c176ca781be935dc9bef00e50a9198"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.i686-linux-musl-cxx11.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96f189c27cd094c2a819c7aadf3bc6c960654c6b"
os = "windows"

    [[Clp.download]]
    sha256 = "934e10517b9b90b780869a46177c8d140ef333fab6458432637ce4bae8dc043d"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.i686-w64-mingw32-cxx11.tar.gz"
[[Clp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f659128c52d77209f544f1e78bfc516f3d32009b"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "fb3933a4b13d11336266c3df9f82d36710036d4dad4d6fcddbfde184ec232786"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
git-tree-sha1 = "b4139a6680b56d635dac4bea025ec28278ef34f9"
os = "macos"

    [[Clp.download]]
    sha256 = "5d4bdb4eaa3c902ecadc1d6493d6778f82ecb743f810b4d326f30b4ab3e1d81d"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.x86_64-apple-darwin.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c141839532fa90c2ef5a9128051673bac1c8765"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "288dcc47ece2e65fd9917946d06ffbba066db3c7981979b2ed616a7901fadbda"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.x86_64-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6481c9958e2cda91f54378575d390d12ecabdf57"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "22098b9fbd67ebd64804f916d815f36f6bfe9b95d1f3705bc787e85084dfb965"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.x86_64-linux-musl-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e541e6b576429bf9c007361d71f1b3c590abe9c"
os = "windows"

    [[Clp.download]]
    sha256 = "45e31b36127ce642ae800589c90c51e7de5570d7c46ab6a3a68fc33c713102ad"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v100.1700.1001+0/Clp.v100.1700.1001.x86_64-w64-mingw32-cxx11.tar.gz"
