[[Clp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad78bfc962f52bb851f2301403c348e5647b9375"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "d264d29547dbb5acf25a0eaae98287ca8261477229d0df84d242f7e967ebacc3"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.aarch64-linux-musl-cxx03.tar.gz"
[[Clp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "520cebf1a29bc53b99144f04bd6ac61e507008c2"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "1b2e0402e75f72036abf4403b236ff9c6a5215352d8eb73ea19176ac021219de"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.aarch64-linux-musl-cxx11.tar.gz"
[[Clp]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d51fa6b952803a7da72d5d0c2921b10d7959d64"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "10469894c5ecb5c553a65f38120ae30e6006adadbd50e0fe352c1cdfda4d291d"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba0bdab6bb08e33404e392e892271af64068da2d"
os = "windows"

    [[Clp.download]]
    sha256 = "8116fadde3e9046f37798ee65dfd5fbee29ec6a7d1a4a97775995f16abe88c93"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-w64-mingw32-cxx11.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e238bc15c85f27a6561ca8a6f652bad555b90db"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "fef5e73b06fa611e643a16025ee4b93510bb1a1721beda4e3276935106b5d26f"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.i686-linux-musl-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f52dde4b37f13238e8bc11b3c538773f64faf87"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "7d012a62567bbcbb316fc18c54c26bc8deb766c697d92fa1b02c5a6abe5782ab"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-linux-musl-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86ecf44c00d0b16990313b2e69be48a68ed42ff5"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "078930979d59abdae8b288c7c16eee3bbde7390338d777305ff779277ab7239c"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "031aa3700a1598f23316ca4055d2e486e0896301"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "c94fedd321f775971ff181864d61dd3f7731de18f98edecedd48c29b231a6eb3"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.i686-linux-gnu-cxx03.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "396708ad058ae6c4f6d3945282a357e4cf8c8d63"
os = "macos"

    [[Clp.download]]
    sha256 = "fa0e038e562bbcb2a492f4ae8e1b6fb9d40ef668016496499911545d2ff1a487"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55724e15730aba712450a45416e7ad29f08db68b"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "72b5293132ebc5a1f6ecb459696542dcf9145f5c613ef5fadd727fc9f960cd62"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.i686-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51094994af289e837ab3fe384879dfa3b85f1c28"
os = "windows"

    [[Clp.download]]
    sha256 = "9428e6b99cdc4405330993c01b12a409e4c596e7ad571448f26a06b6cfe06ed3"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cf32528460420740b8ba41eb7a2833b8975b4c2"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "7095e2dde24617fb1b5c14f2b97718837c0336ec15271f1b2bab3c15e308271e"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af9e695fb44e6cfaf0113edba86b2c10f403a49f"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "742a3d7f4ea6db06e5bb8c96bcb7e9730c34a636302e25e776353a3e178c6105"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c909d1a82a30fb0ec25ed9c5ae19ff6fb81d870"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "95049153b496cdca593ceb0bb849c91189d4408b8817c8e5b66337232127a9bf"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-linux-musl-cxx03.tar.gz"
[[Clp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af648a8e3cfdb55ead51ceb4c94eb5060295b261"
os = "macos"

    [[Clp.download]]
    sha256 = "4383a5514512baf232a79ac648221e3f08f4032c8c70ce4710ed467706a0aecc"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b07f01f85d905693a8b8032ccc0e58dc7d443d5"
os = "windows"

    [[Clp.download]]
    sha256 = "c19e1e3abc48582d077be6e05b08063a05eb77e511db065ffb2d0ca6120e8807"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.i686-w64-mingw32-cxx03.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15e6eeadbcd9a6ac03c1ee107464bc4695d27a09"
os = "windows"

    [[Clp.download]]
    sha256 = "596fd8cc244b772595e7dbd0c8384b6c53b16e36b27bfaf95037b3bc0f62f39d"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.i686-w64-mingw32-cxx11.tar.gz"
[[Clp]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d5b65716b204b8b4324c145835839d42f54fd5e"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "72a9b502632c55ff11f63645efc09d3e10b795b76c9608ea9a5117476b171ec4"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clp]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a1f29c555f9974d0441e525277216c610ebcaa7"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "fa7be6c24de8aec4c3eb1baecac225459c201e93e1ec19ca8ddb6307ee35f090"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85fb25e19986a187809403f1c3aa97946f36cfa4"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "f2f266107269181ed8231cf3bee7a988103c846c72a24d972adb808b708da6aa"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Clp]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fd9b2f2367e9afc0127e4cca1e074b461fd4eec"
libc = "glibc"
os = "linux"

    [[Clp.download]]
    sha256 = "5ea6ed137e0621c02edceeb5fa89b7be8bc3e6d535ecaa006f1c8cf6cd5f67c9"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7df0fc932f2c97fc800d6d42fdd09c2b5b492343"
libc = "musl"
os = "linux"

    [[Clp.download]]
    sha256 = "e7aec1be948501f690ea23c0c9096efabfe02bcad2f95eb364f98bafa4e830f3"
    url = "https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/download/Clp-v1.17.5+1/Clp.v1.17.5.i686-linux-musl-cxx03.tar.gz"
