name = "Clp_jll"
uuid = "06985876-5285-5a41-9fcb-8948a742cc53"
version = "100.1700.1000+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
libblastrampoline_jll = "8e850b90-86db-534c-a0d3-1478176c7d93"
MUMPS_seq_jll = "d7ed1dd3-d0ae-5e8e-bfb4-87a502085b8d"
CoinUtils_jll = "be027038-0da8-5614-b30d-e42594cb92df"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Osi_jll = "7da25872-d9ce-5375-a4d3-7a845f58efdd"
METIS_jll = "d00139f3-1899-568f-a2f0-47f597d42d70"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.9"
MUMPS_seq_jll = "=500.800.100"
CoinUtils_jll = "=200.1100.1200"
libblastrampoline_jll = "5.4.0"
Libdl = "< 0.0.1, 1"
METIS_jll = "=5.1.2"
Osi_jll = "=0.10800.1100"
Artifacts = "< 0.0.1, 1"
