name = "Clp_jll"
uuid = "06985876-5285-5a41-9fcb-8948a742cc53"
version = "1.17.5+1"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
CoinUtils_jll = "be027038-0da8-5614-b30d-e42594cb92df"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Osi_jll = "7da25872-d9ce-5375-a4d3-7a845f58efdd"
METIS_jll = "d00139f3-1899-568f-a2f0-47f597d42d70"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
ASL_jll = "ae81ac8f-d209-56e5-92de-9978fef736f9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
CoinUtils_jll = "=2.11.4"
Osi_jll = "=0.108.6"
METIS_jll = "=4.0.3"
